---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgArIS+w2dk/UYxT7brP6Q3C0WOipIBrQioKyIu4kOt4ei1vE8N6QRhQR2tjNUAbFbGNlanwIBB0oJpzm87MVvEOIEER/XCynYbGqg0OUS6F1GmNwENN0anb4I4hQ+MshbG7q8miSKsP3aBLME3K7TFytwwpvwyjddMEb4qecWo0mnZRO1tAKa9znIG0j9pXuGlPA6rYWsHhwwByoswA+2pWyaHKmwTf3+vI+Bc/bgYWwZ0rqFFZxd/gFwwocUdeDt33tV9TymgGcRUqWkdBR2WVcAM8XUwZfJiWu4khbzzZGyTkQe7TVUUEQqZSw+iS+JOWlAvkwXmUDYoLLT0PTVMTQj4fMWIkBXyGWj3SLzAjwi/6jRmnnHqp835SuykZmJYfsI4+HXygXLGNoC3W2cYzN6lftrt3ITNY7HXeDQ83pwvhL+sf//Kz8SyQ4dgM7+p549w7Q2lOzqsaUt1+z5jdTAgQTB1MdqMg6Y/1aMiXogrRMZlSabEsBEUTwYlc5M1vL4xcZefRU5Kl0cZqCgugNajT61x7K+lJe85U2RNYjAGl+dVfjL67lQ9LkI0qUyDZU2DpgTGsGP1smL3p7gWOsRnnwrBicNaVlP4lpLZJyswRsnUogC+ojcJZ0+wTPPy3K+7PUhmgs2j2+Gh4iPEQ47eH6Ang7YdTZ9/K/7fOMqOCyXwMyrDiSiWOivcaFVguCluEcs0v3mrfRL6x6vPBuEZQWMw/Kec=
    admin-user: AgB8GoQUB0l2PIZeeJCWeQI8xdoeIsyv6q6JZmh5wAYtSjEJ2RHcwjatTNSU4/PiIuB/EDMAysPTlep+cn6pUqIrHcVoB9I4HrvBejhBGKisjW95xNzJw/iV34A4KUmwFNo/WXKWF8Emvf+EfCNmbr5nRNmKRsQP+gv+9NFx1T0HVFabMfig0ElOzS8b8hbmUjNS/0jtYOWYW2sesmdlXPwrzV3tjEfqdvJBm12qDv6WJcIcbzGueqr5UITgBvAgxc6IC7W8gj1Cnhg1OB/6hRiyF8KOEwD7voGoQGhYfi2GF/xT2/iWf9i5voLPwekY0EeikU2yqxIgOto2A3GlOdERQ6NbYhozRVwxFj/WK63Lc/49b86eWCtecw2k/XpcD3oXN7cseJ2yzto4MbsosxYD9lHuqrAo6xHOUN9jBBvGoHRct/TM4FPq33v3YwlQQ1Rp1fPE4FX8nvaok4RjFSG08Cp/Jl/eYwP5xrlbE6pPjSsOkMjmjxSA5dbbGfHPS0KhLYGvr2haZwiWxz9xZCkjWnvt4k9+ZoXK4vxAM2sCrWdEqpx0H5BIycFfLQsSOHfeu1gf7cy8Vddp96cpvMVLUwT4iRAOsKeBvCdgWfEkDiMz4B29CWWIq8WXhcDUEUqX0CCyS5u697zl1YTTqzshm4H7uTEKjK3y+gVMm+0RjH5a7NXpQxFGXznikyM7hG8+hcuz2g==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
