config:
  clients:
    - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

  snippets:
    pipelineStages:
      - cri: {}

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    memory: 128Mi

# Собираем логи со всех узлов, включая изолированный узел БД
tolerations:
  - operator: Exists

serviceMonitor:
  enabled: false
