crds:
  enabled: true
  keep: true

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    memory: 128Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi

cainjector:
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 256Mi
